### ISSUE TITLE
Fatal error while using Writer\xlsx

### ISSUE THREAD

**Issue by to175** [PHPOffice/PhpSpreadsheet#202] opened 2017-08-20 13:47 UTC
Hi I have an error, help me please... What is the problem please ?

### What is the expected behavior?
I want to create a XLSX file

### Code ?
`<?php
require 'phptoexcel/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Hello World !');

$writer = new Xlsx($spreadsheet);
$writer->save('hello world.xlsx');
?>`

### What is the current behavior?
There is fatal error : 
**( ! ) Fatal error: Class 'PhpOffice\PhpSpreadsheet\Writer\Xlsx' not found in C:\wamp64\www\timax\test.php on line 12**

### Which versions of PhpSpreadsheet and PHP are affected?
Last version with PHP 7

**Comment by GreatHumorist** [comment] 2017-08-20 14:23
Because you havn't import Xlsx class yet, suggest you move use statement to the top, and you should add a statement "use PhpOffice\PhpSpreadsheet\Writer\Xlsx;" so that you can use the Xlsx writer.

Besides, you can also import IOFactory to make a xlsx waiter.

**Comment by to175** [comment] 2017-08-20 14:29
Sorry, I have modified, this is the right code, i have already Xlsx thats why i dont understand the issue...
Thanks for replying tho :)
What can i do now ? is IOFactory necessary ?

**Comment by GreatHumorist** [comment] 2017-08-20 14:33
Not really need at all, just a suggest, because use factory pattern may be a little better.

Best wishes.

**Comment by to175** [comment] 2017-08-20 14:46
Even if I have use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
I stille have the error

**Comment by GreatHumorist** [comment] 2017-08-20 14:50
Have you download the phpSpreadsheet? Have you execute "composer install" command? Are 'phptoexcel' is the correct folder of phpSpreadsheet?

**Comment by to175** [comment] 2017-08-20 15:00
I don't like using commands so I used this https://php-download.com/package/phpoffice/phpspreadsheet

**Comment by GreatHumorist** [comment] 2017-08-20 15:07
Is it solved?

**Comment by to175** [comment] 2017-08-20 15:14
It is not, with the package I have not to use composer, so I have put the files in my directory and launched a php page, it should have worked but it didnt cf the fatal error

**Comment by GreatHumorist** [comment] 2017-08-20 15:35
Just now I download "https://php-download.com/package/phpoffice/phpspreadsheet" and use it for your code, there's no error occurred.

**Comment by to175** [comment] 2017-08-20 15:40
Thanks :) Maybe I do it wrong somewhere... I have put the content of zip in phptoexcel directory and thats all...

**Comment by GreatHumorist** [comment] 2017-08-20 15:45
Can you show your dir tree?

**Comment by to175** [comment] 2017-08-20 16:53
for example it is C:\wamp64\www\timax\phptoexcel\src\PhpSpreadsheet\Writer

**Comment by PowerKiKi** [comment] 2017-08-21 08:19
I am closing this, because it is not a bug within PhpSpreadsheet but a support question about usage. But feel free to keep the discussion going...

**Closed by PowerKiKi** 2017-08-21 08:19 UTC

**Comment by PowerKiKi** [comment] 2017-08-21 08:36
By the way, php-download.com is not recommended, because it includes dev dependencies that you would not need (making the package much bigger that what it should be). Future updates will be harder and managing conflicts between several libraries in your project won't be possible. I strongly encourage you to start using composer instead.

**Comment by ikko** [comment] 2017-09-12 06:50
same happened with me using dev-develop. use Version 1.0.0-beta instead.

**Comment by PowerKiKi** [comment] 2017-09-12 14:42
You are either using composer incorrectly, or not using at all. If you are not familiar with it, you should read about it over there: https://getcomposer.org/doc/
