### ISSUE TITLE
Cell Class not found

### ISSUE THREAD

**Issue by alejandr0** [PHPOffice/PhpSpreadsheet#281] opened 2017-12-03 11:15 UTC
This is:

- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

A class not found exception is sent after updating to the last dev-master version.
The Cell Class exists in /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php

### What is the expected behavior?
To not to get this Exception

### What is the current behavior?
An exception is thrown when using the Cell Class
"Symfony\Component\Debug\Exception\FatalThrowableError: Class "PhpOffice\PhpSpreadsheet\Cell"; not found"

### What are the steps to reproduce?
1- Include the library
`use PhpOffice\PhpSpreadsheet\Cell;`
2- Try to use it
`Cell::setValueBinder(new Cell\AdvancedValueBinder());`

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
Cell::setValueBinder(new Cell\AdvancedValueBinder());

```

### Which versions of PhpSpreadsheet and PHP are affected?

"PHPOffice/PhpSpreadsheet": "dev-master",

**Comment by PowerKiKi** [comment] 2017-12-04 04:57
Duplicate of #278

**Closed by PowerKiKi** 2017-12-04 04:57 UTC
