### ISSUE TITLE
PHP 7.1: Numbers shown with scientific notation even if explicitely formatted as text

### ISSUE THREAD

**Issue by oveach** [PHPOffice/PhpSpreadsheet#357] opened 2018-02-02 16:59 UTC
This is:

```
- [x] a bug report
```

With PHP 7.1, if I put a number in a cell and set explicitely a text format, it's shown with scientific notation in Excel, instead of showing the number "as is".

Maybe related with this BC break introduced in 7.1?
https://secure.php.net/manual/fr/migration71.incompatible.php#migration71.incompatible.numerical-strings-scientific-notation

It's worth to know that it works perfectly fine in LibreOffice 5.4!

### What is the expected behavior?
Numbers shown as real text (ex : 150000197301), because I explicitely specify a text format style.

### What is the current behavior?
Numbers shown with scientific notation (ex: 1,5E+11).

### What are the steps to reproduce?
The following code works as expected with PHP 5.6 (value shown = 150000197301), but fails with PHP 7.1 (value shown = 1,5E+11).
```php
<?php
require 'vendor/autoload.php';
$data = array('foo' => '150000197301');
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getSheet(0);
$sheet->fromArray($data, null, 'A1');
$sheet->getStyle('A1:A1')
    ->getNumberFormat()
    ->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_TEXT);
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$filename = 'test_' . PHP_VERSION . '.xlsx';
$writer->save($filename);
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreasheet 1.1.0
PHP 7.1.2
Tested on Windows french and Excel 2016 french.

**Comment by PowerKiKi** [comment] 2018-02-11 07:04
I actually cannot reproduce that on PHP 7.1 nor 7.2. I'll close it for now. But feel free to comment further if you find out how to reproduce systematically.

![image](https://user-images.githubusercontent.com/72603/36070761-2432af0c-0f45-11e8-95f5-c7b8e6c4376d.png)

**Closed by PowerKiKi** 2018-02-11 07:04 UTC

**Comment by oveach** [comment] 2018-02-12 09:26
The screenshot you posted shows that you actually reproduced the problem!

This is how it looks in Excel with PHP 5.6 :
![image](https://user-images.githubusercontent.com/312756/36090023-ecd77d54-0fde-11e8-8017-4b0a3f3753de.png)

You see the difference?
The problem is not the content of the cell itself, but  how it's displayed in the table.

**Comment by PowerKiKi** [comment] 2018-02-25 17:21
Still cannot reproduce. Here is a comparison of PHP 5.6 and PHP 7.1 side by side. They show exactly the same way:

![image](https://user-images.githubusercontent.com/72603/36644259-c8691788-1a57-11e8-964f-c04118823d12.png)


This also correspond to Excel 2016 behavior if I input 150000197301 into the formula bar for cell A1 manually, and then change formatting to "text".

**Comment by username31480** [comment] 2019-02-12 17:15
I have seen this problem described as resulting from 32-bit vs 64-bit php.  I am using 64-bit php.
The problem is that the number is displayed as "1.5E+11" in the table cell A1.
![image](https://user-images.githubusercontent.com/20046451/52653983-a8a7b700-2eb6-11e9-9709-83f7d990e44d.png)

The objective is to have the the values displayed as "1500000197301" in the table cell A1.
When the cell format is set to "text" it should display the value as "text" in table cell A1.
<img width="467" alt="capture" src="https://user-images.githubusercontent.com/20046451/52654303-54510700-2eb7-11e9-8235-b81b24eee08a.PNG">

**Comment by stefanhuber** [comment] 2019-02-22 09:16
Also same problem here! It seams to be impossible to save a number as text.

**Comment by webmindstech** [comment] 2019-03-20 10:30
Add white space to your data 
$data = array('foo' => '150000197301 ');

**Comment by Yavor-Ivanov** [comment] 2019-03-26 16:05
I was having the same issue with an XLSX export/import code I was writing. I needed:
  1. Very large values (like SSN's) to **not** show up in scientific notation.
  2. To not modify the cells values in any way, as it will need to be read by importing code.
  3. Be able to modify the value of the cell in Excel (or other spreadsheet programs) and not disturb the text formatting.

I've tried stefanhuber's solution and, while the cells looked okay, editing yielded trouble:
<img width="230" alt="Screenshot 2019-03-26 at 17 43 24" src="https://user-images.githubusercontent.com/5585316/55011745-0a4b5d00-4fef-11e9-9fc5-8be465fa5d9d.png">
<img width="240" alt="Screenshot 2019-03-26 at 17 43 34" src="https://user-images.githubusercontent.com/5585316/55011783-18997900-4fef-11e9-8a37-d1163675567b.png">

As you can see, clicking on the field to edit it reveals the formula.

webmindstech's solution was more subtle, but you can still see the space when trying to edit. It's hard to see, so I've highlighted it in the second screenshot:
<img width="257" alt="Screenshot 2019-03-26 at 17 44 47" src="https://user-images.githubusercontent.com/5585316/55011910-4a124480-4fef-11e9-862f-2130d288592c.png">
<img width="243" alt="Screenshot 2019-03-26 at 17 45 00" src="https://user-images.githubusercontent.com/5585316/55011921-4d0d3500-4fef-11e9-9cc3-e1a017fb7b30.png">

I dug around in the [PHPSpreadsheet documentation](https://phpspreadsheet.readthedocs.io/en/stable/topics/recipes/#explicitly-set-a-cells-datatype) and managed to cobble this together:

```php
// @Note: You don't need to format the cell as text if you're
// only interested in displaying it correctly to the user, but
// the cell value will revert to scientific notation as soon as
// the user edits the cell in Excel, unless you've set the
// formatting.
$worksheet
    ->getStyleByColumnAndRow($columnIndex, $rowIndex)
    ->getNumberFormat()
    ->setFormatCode(NumberFormat::FORMAT_TEXT)
;

$value = $worksheet->getCellByColumnAndRow($columnIndex, $rowIndex);
// @Note: This is the actual bit of magic, which allows you to
// force the cell value type. If you don't explicitly set the type,
// PHPSpreadsheet tries to implicitly convert it, which is where
// we run into trouble.
$worksheet->getCellByColumnAndRow($columnIndex, $rowIndex)->setValueExplicit(
    $value,
    \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING
);
```

Here's the results of doing things this way:
  1. Large numbers display correctly as text:
    <img width="252" alt="Screenshot 2019-03-26 at 17 58 51" src="https://user-images.githubusercontent.com/5585316/55013013-facd1380-4ff0-11e9-9930-22fe08588a54.png">
  2. Nothing unexpected surprises when editing the cell, and the formatting is retained after edits:
    <img width="949" alt="Screenshot 2019-03-26 at 17 59 16" src="https://user-images.githubusercontent.com/5585316/55013138-37990a80-4ff1-11e9-9978-c5f4edcece1f.png">

**Comment by epedder** [comment] 2019-06-28 19:24
None of these solutions worked for me.  However I resolved the problem by using "#" instead of NumberFormat::FORMAT_TEXT, which is essentially custom formatting.

```
$worksheet
    ->getStyleByColumnAndRow($columnIndex, $rowIndex)
    ->getNumberFormat()
    ->setFormatCode('#')
;
```

**Comment by MarkBaker** [comment] 2019-07-01 07:07
If you don't want a large number to be dispayed using scientific format, then you don't store it as a number, but as text, using `setCellValueExplicit()`. The value must be __stored__ as a string to avoid loss of precision. Simply specifying a number format mask of text will not change the underlying value, number format is for display purposes.

**Comment by epedder** [comment] 2019-07-02 16:33
@MarkBaker you are right that the value should be stored as a string.  However, Excel will display strings in scientific notation even if you set the display format to be text.

```php
$cell->setDataType(DataType::TYPE_STRING);
$style = $this->sheet->getStyleByColumnAndRow($columnIndex, $this->rowIndex);
$style->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_TEXT);
```
Results in

![image](https://user-images.githubusercontent.com/9807810/60518366-60473500-9caf-11e9-9f99-03a9d75e1480.png)

While

```php
$cell->setDataType(DataType::TYPE_STRING);
$style = $this->sheet->getStyleByColumnAndRow($columnIndex, $this->rowIndex);
$style->getNumberFormat()->setFormatCode('#');
$style->getAlignment()->setHorizontal(Alignment::HORIZONTAL_LEFT);
```
Results in

![image](https://user-images.githubusercontent.com/9807810/60518513-ad2b0b80-9caf-11e9-8b86-89d19d261b55.png)

**Comment by Jedliu** [comment] 2019-07-07 12:02
> @MarkBaker you are right that the value should be stored as a string. However, Excel will display strings in scientific notation even if you set the display format to be text.
> 
> ```
> $cell->setDataType(DataType::TYPE_STRING);
> $style = $this->sheet->getStyleByColumnAndRow($columnIndex, $this->rowIndex);
> $style->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_TEXT);
> ```
> 
> Results in
> 
> ![image](https://user-images.githubusercontent.com/9807810/60518366-60473500-9caf-11e9-9f99-03a9d75e1480.png)
> 
> While
> 
> ```
> $cell->setDataType(DataType::TYPE_STRING);
> $style = $this->sheet->getStyleByColumnAndRow($columnIndex, $this->rowIndex);
> $style->getNumberFormat()->setFormatCode('#');
> $style->getAlignment()->setHorizontal(Alignment::HORIZONTAL_LEFT);
> ```
> 
> Results in
> 
> ![image](https://user-images.githubusercontent.com/9807810/60518513-ad2b0b80-9caf-11e9-8b86-89d19d261b55.png)

This solves my problem successfully! Thank you!

**Comment by MarkBaker** [comment] 2019-07-08 16:47
```
$cell->setDataType(DataType::TYPE_STRING);
```
Does not automagically convert numeric values that have already been loaded into a cell to a string.

If you want to store a numeric value as a string, then use `setCellValueExplicit()` instead of `setCellValue()`.

**Comment by Jedliu** [comment] 2019-07-09 01:05
`setValueExplicit( $value, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING);`
This works but not always. I did the test and found that when you opened the excel by Numbers in MacOS it was displayed correctly but it's still in scientific notation in Excel (both MacOS and Windows).

`getNumberFormat()->setFormatCode('#');`
This works both for Numbers and Excel. However, if the number starts with 0 and when you try to edit the value when you double click it, the numbers will be shown without 0. That's really wired.

![image](https://user-images.githubusercontent.com/771703/60851996-8d07c900-a228-11e9-81a0-b2a65e86d27e.png)
After double click to edit:
![image](https://user-images.githubusercontent.com/771703/60852036-a0b32f80-a228-11e9-8221-0995fe0f05bf.png)

**Comment by prinze77** [comment] 2019-07-24 15:41
Its 2019 almost 2020! Why this issue still exists?

**Comment by gianlucag** [comment] 2019-08-04 09:50
> Its 2019 almost 2020! Why this issue still exists?

because Excel sucks

**Comment by thanhkhanhcntt** [comment] 2019-08-04 14:56
> > Its 2019 almost 2020! Why this issue still exists?
> 
> because Excel sucks and that's what you get when you want to force something which hasn't designed to be a database to be a database

It's not because of excel. Before I copy data and paste to excel, I choose all cells and format them to text. After pasting, everything work perfect. Problem is at the framework, not excel,

**Comment by supportreq** [comment] 2019-09-05 14:14
We tried the above but for cell values starting from 1-9 are getting a leading '

How do we get an excel without starting '

**Comment by georgetony** [comment] 2020-01-21 08:35
One possible solution is to use RichText (use **PhpOffice\PhpSpreadsheet\RichText\RichText**)

**Example:**
$val = 896503031905050127; // Any long numerical text.
$rt = new RichText();
$rt->createText($val);

// Adding the above to a cell
// $col = 'A'; $row = 2;
$sheet->setCellValue($col.$row, $rt);

When the sheet is opened in Excel, the value is displayed as text. Not truncated or sci. notation.

If you edit the cell in Excel, _it will re-format to sci. notation_. **Solution:**

When you create the Excel template XLSX, format entire columns as Text. Then populate the cells using the above code. Now you can edit the values and the values will stay as text. 

**Tested on:**
Excel for Mac, version 16.33 (20011301).
PhpOffice\PhpSpreadsheet\Spreadsheet, version [1.8.2] - 2019-07-08

**Comment by delboy1978uk** [comment] 2020-02-27 12:10
Why has this issue not been reopened? 2 years on and people are still having this issue!

**Comment by delboy1978uk** [comment] 2020-02-27 12:15
@georgetony  thanks for your suggestion, it helped resolve my issue, but I still consider it to be a cheap hack! This issue should be reopened IMHO

**Comment by myzticman** [comment] 2020-07-24 03:48
Agree with @delboy1978uk, issue still exists - unsure why this isn't considered a bug. Setting formatting to '@' does not work. For those interested, it'll work if you set formatting to '#'.
In our case we were using PhpSpreadsheet to construct a CSV file from array, so explicitly setting every single field wasn't ideal.

**Comment by titansoftime** [comment] 2021-02-08 15:26
This is still an issue. It's unfortunate that this has not only failed to be repaired but has been outright neglected. Thankfully people in this thread found some useful workarounds.

**Comment by coisox** [comment] 2021-03-03 10:00
> One possible solution is to use RichText (use **PhpOffice\PhpSpreadsheet\RichText\RichText**)
Thank you @georgetony georgetony . Your solution works for me (March 2021). Like you said, using RichText solve the first issue (view properly), then combining with this solved the edit issue:
`$sheet->getStyle('A1')->getNumberFormat()->setFormatCode('@')`

**Comment by JorgeOlmedos** [comment] 2021-07-23 11:21
no funcionaaaaaaaa

**Comment by warwickchapman** [comment] 2021-09-02 10:53
Suggest this is re-opened or someone from the development team detail why it has been marked invalid and closed.

**Comment by PowerKiKi** [comment] 2021-11-01 04:47
@warwickchapman, Mark has been answering multiple times to explain how things work. And AFAIK nobody were able to provide a reproducible case that is correct. The issue is thus closed because it is working as expected, even though some users have the wrong expectations about what the code is supposed to do.

If you really think something is wrong, then at the bare minimum create a PR that exhibits the bug, or better yet include a fix in the PR.
