### ISSUE TITLE
0 in cells after toArray() is value null

### ISSUE THREAD

**Issue by ArmandArthur** [PHPOffice/PhpSpreadsheet#1668] opened 2020-10-05 13:27 UTC
Hello,

I have "0" in my cells.

I do :

`$sheet = $spreadsheet->getSheet($index_sheet);
 $sheetData  = $sheet->toArray(null, true, true, true);`

And the value of the cell is null....

How allow the zero like one, two, etc....?

**Comment by alexgunkel** [comment] 2020-10-24 10:28
Hi,

can you provide more information, e.g. the file your read in? I tried to reproduce what you report but in my example the value of the cell is always 0.

**Comment by ArmandArthur** [comment] 2020-10-24 23:26
It's OK, i had modify the librairie.

**Comment by rafibr** [comment] 2020-12-09 12:37
> It's OK, i had modify the librairie.

Can you please show me how you have modified the library? Thanks a lot

**Comment by ArmandArthur** [comment] 2020-12-09 16:09
At vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Worksheet\Worksheet.php

Ligne  2574 👍 

`                    if ($cell->getValue() != '' && $cell->getValue() != '0') {
                        if ($cell->getValue() instanceof RichText) {
                            $returnValue[$rRef][$cRef] = $cell->getValue()->getPlainText();
                        } else {
                            if ($calculateFormulas) {
                                $returnValue[$rRef][$cRef] = $cell->getCalculatedValue();
                            } else {
                                $returnValue[$rRef][$cRef] = $cell->getValue();
                            }
                        }

                        if ($formatData) {
                            $style = $this->parent->getCellXfByIndex($cell->getXfIndex());
                            $returnValue[$rRef][$cRef] = NumberFormat::toFormattedString(
                                $returnValue[$rRef][$cRef],
                                ($style && $style->getNumberFormat()) ? $style->getNumberFormat()->getFormatCode() : NumberFormat::FORMAT_GENERAL
                            );
                        }
                    } 
                    else if($cell->getValue() == '0') {
                        // Cell holds a NULL
                        $returnValue[$rRef][$cRef] = '0';
                    }
                    else {
                        // Cell holds a NULL
                        $returnValue[$rRef][$cRef] = $nullValue;
                    }
                }`

**Comment by ArmandArthur** [comment] 2020-12-09 17:44
I don't know why le code  format doesn't work.

**Comment by rafibr** [comment] 2020-12-09 18:03
It's work, thanks a lot...

> I don't know why le code format doesn't work.



> At vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Worksheet\Worksheet.php
> 
> Ligne 2574 :
> 
> `if ($cell->getValue() != '' && $cell->getValue() != '0') {
> if ($cell->getValue() instanceof RichText) {
> $returnValue[$rRef][$cRef] = $cell->getValue()->getPlainText();
> } else {
> if ($calculateFormulas) {
> $returnValue[$rRef][$cRef] = $cell->getCalculatedValue();
> } else {
> $returnValue[$rRef][$cRef] = $cell->getValue();
> }
> }
> 
> ```
>                     if ($formatData) {
>                         $style = $this->parent->getCellXfByIndex($cell->getXfIndex());
>                         $returnValue[$rRef][$cRef] = NumberFormat::toFormattedString(
>                             $returnValue[$rRef][$cRef],
>                             ($style && $style->getNumberFormat()) ? $style->getNumberFormat()->getFormatCode() : NumberFormat::FORMAT_GENERAL
>                         );
>                     }
>                 } 
>                 else if($cell->getValue() == '0') {
>                     // Cell holds a NULL
>                     $returnValue[$rRef][$cRef] = '0';
>                 }
>                 else {
>                     // Cell holds a NULL
>                     $returnValue[$rRef][$cRef] = $nullValue;
>                 }
>             }`
> ```

**Comment by oleibman** [comment] 2023-11-16 04:40
Closing. Unable to reproduce problem in current version, nor in 1.14.1 nor 1.15.0 which would have been the current version at the time.

**Closed by oleibman** 2023-11-16 04:40 UTC
