### ISSUE TITLE
Invalid datatype: d with XLSX

### ISSUE THREAD

**Issue by mikaelz** [PHPOffice/PhpSpreadsheet#2624] opened 2022-02-26 10:14 UTC
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the current behavior?
Getting exception `Order 0 error: Invalid datatype: d`

### What are the steps to reproduce?
The XLSX sheet XML contains
```
<x:c r="D9" s="15" t="d"><x:v>2022-02-21</x:v></x:c>
```

Loading XLSX via
```php
	try {
		$spreadsheet = IOFactory::load( $_FILES['xls']['tmp_name'] );
		$sheet_data = $spreadsheet->getActiveSheet()->toArray( null, true, true, true );

```

### Which versions of PhpSpreadsheet and PHP are affected?
1.19.0

**Comment by MarkBaker** [comment] 2022-02-26 12:57
Duplicate of [Issue #2373](https://github.com/PHPOffice/PhpSpreadsheet/issues/2373)

**Closed by MarkBaker** 2022-02-26 12:57 UTC
Labels: duplicate
