### ISSUE TITLE
Uncaught Error: Call to a member function attributes() on null

### ISSUE THREAD

**Issue by BadTasTe-** [PHPOffice/PhpSpreadsheet#77] opened 2017-01-20 14:09 UTC
Hi there, here is the error i got:
PHP Fatal error:  Uncaught Error: Call to a member function attributes() on null in /var/www/htdocs/syncro/V3.0/autosyncro_modules/PhpSpreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php:401

This is the xl/theme/theme.xml of the file:
<?xml version="1.0" encoding="utf-8"?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Office Theme"><a:themeElements><a:clrScheme name="Office"><a:dk1><a:sysClr val="windowText" lastClr="000000" />

but xlsx.php return:
var xmlThemeName: object(SimpleXMLElement)#99 (0) {
}

var themeName : string(0) ""

I'm using phpSpreadsheet to convert hundreds of files to csv every day, it's working well except for some of them, always the same one's.

Thank you for your help

**Comment by PowerKiKi** [comment] 2017-01-20 15:25
The description seems to lack important information to do anything about it. Closing for now, but feel free to add a fully reproducible example of code that reproduce the issue and reopen it.

**Closed by PowerKiKi** 2017-01-20 15:25 UTC

**Comment by Quix0r** [comment] 2017-01-23 10:43
@BadTasTe- are you sure, you use a CSV file with this? Because The failing class in `Xlsx` which hints that your file is maybe an XLSX (new M$ Office format) or your code is something nasty.

Please provide a code as @PowerKiKi asked for.

**Comment by BadTasTe-** [comment] 2017-01-24 09:47
Hi there, thanks for your answer, i'm using this code for hundreds of xls / xlsx / csv files and it works well except for some of them:
`$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($file);
$reader->setReadDataOnly(true);
$reader->load($file);
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($reader, "CSV");
$writer->save("test.csv");`

The XMLThemeName object appears to be empty, so there is no $xmlTheme->themeElements->clrScheme->attributes();

I can't give you the xlsx file here but here is the theme.xml 
[phpSpreadsheet_error_theme.txt](https://github.com/PHPOffice/PhpSpreadsheet/files/726223/phpSpreadsheet_error_theme.txt)

Thanks for your help!

**Comment by manoojm** [comment] 2019-03-25 14:31
I am facing the same issue with couple of xlsx file. Unfortunately, we are not at the liberty to share the files to be able to reproduce in-house for you.

Fatal error: Uncaught Error: Call to a member function attributes() on null in C:\Apache24\htdocs\vendor\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php:1723
