### ISSUE TITLE
Trying to access array offset on value of type null PHP 7.4.13

### ISSUE THREAD

**Issue by safuandgb** [PHPOffice/PhpSpreadsheet#2026] opened 2021-04-26 05:14 UTC
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Read the excel file

### What is the current behavior?
ErrorException : Trying to access array offset on value of type null

### What are the steps to reproduce?
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load(storage_path('template.xls'));

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

    public function test()
    {

        $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load(storage_path('template.xls'));

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet  v 1.16
PHP 7.4

**Comment by darkojelen** [comment] 2021-04-28 07:42
I’m dealing with similar problem. After upgrading to PHP 7.4 

code

`$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');`
`$spreadsheet = $reader->load('file.xlsx');`

produce in log file endless lines of

`[28-Apr-2021 09:12:45] PHP Notice:  Trying to access array offset on value of type int in /php/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/DefaultValueBinder.php on line 56`

**Comment by pronata** [comment] 2021-05-20 11:34
I encountered the same issue. Updating the library "phpoffice/phpspreadsheet" to "^1.10" helped me.

**Comment by oleibman** [comment] 2021-05-20 14:46
Can either of you share the file which is causing this problem? And please confirm your version of PhpSpreadsheet.

**Comment by darkojelen** [comment] 2021-05-20 18:16
I hope that this could help.

[example.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/6517968/example.zip)

**Comment by oleibman** [comment] 2021-05-20 19:21
No luck duplicating your problem with read-x.php as you supplied it on any of master, 17.1, or 16.0 releases, running with PHP 7.4.14. Results in each case:
```
array(2) {
  [0]=>
  int(1)
  [1]=>
  array(1) {
    [1]=>
    array(1) {
      ["A"]=>
      string(1) "A"
    }
  }
}
```

**Comment by safuandgb** [comment] 2021-05-21 01:39
Hi @oleibman ,

Did you enable your notice error reporing?

The output for read-x.php using PHP 7.4.13 is

$ php read-x.php
PHP Notice:  Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 133

Notice: Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 133
PHP Notice:  Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 134

Notice: Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 134
PHP Notice:  Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 137

Notice: Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 137
PHP Notice:  Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 138

Notice: Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 138
PHP Notice:  Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 144

Notice: Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 144
PHP Notice:  Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 145

Notice: Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 145
PHP Notice:  Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 146

Notice: Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 146
PHP Notice:  Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 147

Notice: Trying to access array offset on value of type null in C:\Users\dgb\Desktop\Workspace\example\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 147
array(2) {
  [0]=>
  int(1)
  [1]=>
  array(1) {
    [1]=>
    array(1) {
      ["A"]=>
      string(1) "A"
    }
  }
}

**Comment by oleibman** [comment] 2021-05-21 02:20
I added the following statements:
```
	echo $name;
	echo 'abc'{1}, "\n";
```

And my output is now:
```
Deprecated: Array and string offset access syntax with curly braces is deprecated in C:\git\example\read-x.php on line 18
array(2) {
  [0]=>
  int(1)
  [1]=>
  array(1) {
    [1]=>
    array(1) {
      ["A"]=>
      string(1) "A"
    }
  }
}

Notice: Undefined variable: name in C:\git\example\read-x.php on line 17
b
```
So, yes, I get notices, but I don't see the notices you are reporting.

**Comment by wacekgocki** [comment] 2021-06-30 21:53
I have the same problem. My error message is:  'Trying to access array offset on value of type int' (errcode: 0). 

I'm calling function:

`$sheet->setCellValueByColumnAndRow(1, 1, 100);`

Then execution goes down to method DefaultValueBinder::dataTypeForValue. Error occurs in line:

`} elseif ($pValue[0] === '=' && strlen($pValue) > 1) {`

The reason of error is that my $pValue is of type int and above line tries to use it as an array ($pValue[0]), which is not allowed for type int. In my opinion the above line should look like this:

`} elseif (is_string($pValue) && $pValue[0] === '=' && strlen($pValue) > 1) {`

**Comment by MarkBaker** [comment] 2021-06-30 22:36
> Then execution goes down to method DefaultValueBinder::dataTypeForValue. Error occurs in line:
> `} elseif ($pValue[0] === '=' && strlen($pValue) > 1) {`

That line of code was fixed in version 1.10.0, 18 months ago

**Comment by wacekgocki** [comment] 2021-06-30 22:52
OK, my fault, sorry. I did 'composer update' before making a comment, but did not check that it stuck on version 1.9.0 because of a problem with some other dependencies. Now I have 1.18.0 and my problem is gone. Thanks.

**Comment by austyking** [comment] 2021-09-04 23:33
Has this issue been fixed now? Or any work around?
I updated to version 1.18.0 but still have this issue on PHP 7.4

**Comment by ytilotti** [comment] 2021-11-10 20:57
Same issue here with error `Trying to access array offset on value of type null` on PHP 7.4.25 and PhpSpreadsheet 1.9.

**1. Upgrade PhpSpreadsheet 1.16**

Working, no error, file readable

**2. Upgrade PhpSpreadsheet 1.17**

Working, no error, file readable

**3. Upgrade PhpSpreadsheet 1.18**

Not working, error `Argument 4 passed to PhpOffice\PhpSpreadsheet\Calculation\LookupRef\LookupBase::checkMatch() must be of the type int, string given` fixed by #2123

**4. Upgrade PhpSpreadsheet 1.19**

No error but file not working, impossible to open with Excel.

**Comment by oleibman** [comment] 2021-11-10 21:20
I still am unable to duplicate the error, with any release, of the only file uploaded so far in connection with this problem. If you have another file with a problem, please upload it.

**Comment by ytilotti** [comment] 2021-11-12 12:03
Sorry @oleibman, I can't share my file and script.
I compare between 1.18 & 1.19 but so much changes to find a way.
I will stay in 1.17 for the moment.

I make some tests. I cleared my script and deleted all cell/col/sheet in my file. I only open/write with this code:
```
$file = 'template.xlsx';
$writer = IOFactory::load($file);
$writerSave = IOFactory::createWriter($writer, 'Xlsx');
$writerSave->setPreCalculateFormulas(true);
$writerSave->save('test.xlsx');
unlink($file);
unset($writer, $writerSave);
```
I can open the file. I don't know if the problem is on reading or writing.

**Comment by mikevaux** [comment] 2021-12-16 11:10
A couple of things to add to this thread (I was experiencing the same behaviour as OP)

* I think the OP's issue is duplicated in #2315 (the fix references that issue, but not this one, hence me adding the link)
* I think this is fixed in [1.20.0](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.20.0)

**Comment by ytilotti** [comment] 2021-12-16 11:42
I agree with @mikevaux. I have tested with 1.20.0 and all is fine.

**Comment by oleibman** [comment] 2021-12-16 15:10
Thank you for confirming that the issue is resolved. Closing it now.

**Closed by oleibman** 2021-12-16 15:10 UTC
