### ISSUE TITLE
Remove required extensions from Composer.json

### ISSUE THREAD

**Issue by virgofx** [PHPOffice/PhpSpreadsheet#469] opened 2018-04-23 19:58 UTC
The extensions listed as required in `composer.json` that are used in non-core features should all be moved into `suggest` section and the Readme can be updated with more details on which external extensions are required for library calls. This is standard practice and very bad to see a large library requires all these external libraries when in fact it does not.

**Comment by PowerKiKi** [comment] 2018-04-24 04:01
Duplicate of #367

**Closed by PowerKiKi** 2018-04-24 04:01 UTC
