### ISSUE TITLE
conditional style with none border is not preserved when save and load spreadsheet

### ISSUE THREAD

**Issue by ngyuki** [PHPOffice/PhpSpreadsheet#3370] opened 2023-02-16 03:17 UTC
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

conditional style with none border is preserved when save and load spreadsheet.

### What is the current behavior?

conditional style with none border is not preserved when save and load spreadsheet.

### What are the steps to reproduce?

[input.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/10751837/input.xlsx)
[output.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/10751838/output.xlsx)

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;

$book = IOFactory::load(__DIR__ . '/input.xlsx');
IOFactory::createWriter($book, IOFactory::WRITER_XLSX)->save(__DIR__ . '/output.xlsx');
```

### What features do you think are causing the issue

- [x] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

only tested in .xlsx.

### Which versions of PhpSpreadsheet and PHP are affected?

php 8.2.2
phpoffice/phpspreadsheet 1.27.1

**Comment by oleibman** [comment] 2023-02-16 07:48
Confirmed. When border style is 'none', PhpSpreadsheet is omitting the border tag altogether when writing. This is easily fixed, but exposes another problem - color is automatically set when reading border conditional style even when it is not specified in xml. The combination of the two makes regression problems seem unusually likely, so a fix may take a few days.

**Comment by MarkBaker** [comment] 2023-02-16 08:07
I think the issues with defaults on Conditional Styles go a bit deeper still, see [Issue #3202](https://github.com/PHPOffice/PhpSpreadsheet/issues/3202)

I'd been trying to figure a way of allowing nullable properties when the Style is Conditional, including the Style itself, but not for normal Cell styling... I hadn't come up with an answer though.

**Comment by oleibman** [comment] 2023-02-16 08:19
An additional problem is that the spreadsheet produced by Excel has for its conditional border styles `left` 'right` `vertical` `horizontal`, but PhpSpreadsheet produces `left` `right` `top` `bottom` `diagonal`. I am not sure if vertical and horizontal are necessary (or how PhpSpreadsheet would know to generate them), but specifying top and bottom definitely throws the formatting off.

**Comment by oleibman** [comment] 2023-02-16 08:24
Vertical and horizontal appear to not be needed, at least for this particular problem.

**Comment by oleibman** [comment] 2023-02-16 19:28
@MarkBaker I am close to a fix for this problem. I need to write some tests, and also check if it's applicable to the other issue you mentioned. I will have something to push today or tomorrow. Part of the problem is that Border(s) is the only Style element that doesn't have special processing for Conditional. It should have, and that's easy to fix. I will submit the PR as a draft to give you a chance to confirm that it's not thwarting any long-term plans.

I won't be able to do anything about vertical/horizontal for the time being. Since a solution for them isn't needed here, that's okay for now. But ... the pseudo-borders are accessible only in Supervisor mode, and the Reader (and probably the Writer) isn't in Supervisor mode when it reads the Conditional Styles and creates the objects. (I do not have a good understanding of Supervisor mode.)

**Closed** 2023-02-24 06:28 UTC
