### ISSUE TITLE
column-coordinates greater than Z are not working

### ISSUE THREAD

**Issue by netpsirit72** [PHPOffice/PhpSpreadsheet#546] opened 2018-06-11 14:14 UTC
This is a bug report!

Column-coordinates greater than Z are not working

```php
<?php
require __DIR__ . '/vendor/autoload.php';
// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
...
$activeSheet->mergeCells("Z1:AA1");
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.3.0

**Comment by PowerKiKi** [comment] 2018-06-11 17:22
Duplicate of #545 and #521 latest comments

**Closed by PowerKiKi** 2018-06-11 17:22 UTC

**Comment by PowerKiKi** [comment] 2018-06-12 13:44
It's been released as [1.3.1](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.3.1)
