### ISSUE TITLE
unexpected identifier "Closure"

### ISSUE THREAD

**Issue by yjg18com** [PHPOffice/PhpSpreadsheet#3616] opened 2023-06-15 12:09 UTC
This is:

I have a project that requires the use of exported excel and am learning PhpSpreadsheet, but for some reason it always fails to execute in my projects.

Error message
ParseError: syntax error, unexpected identifier "Closure", expecting variable in
/wwwroot/admin/vendor/maennchen/zipstream-php/src/ZipStream.php:111

php 8.02+ phpspreadsheet 1.29

```php
$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Hello World !');

$writer = new Xlsx($spreadsheet);
$file_path = public_path().'/hello_world.xlsx';
$writer->save($file_path);
``` 

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
ubuntu 20.04.6
PHP 8.02
PhpSpreadsheet 1.29

**Comment by maennchen** [comment] 2023-06-15 12:57
ZipStream v3 requires PHP `^8.1` to work. I think you've ignored the plaform requirements when installing your dependencies or are running with a different version than the one used to run composer.

You can force the dependency back to `v2` which is compatible with PHP 8.0 by requiring `"maennchen/zipstream-php": "^2.4"`.

**Comment by oleibman** [comment] 2023-06-19 00:44
A similar problem was solved via https://github.com/PHPOffice/PhpSpreadsheet/issues/3615#issuecomment-1595846986
Perhaps that would also work for you.

**Comment by Benjizle** [comment] 2023-07-03 00:47
> ZipStream v3 requires PHP `^8.1` to work. I think you've ignored the plaform requirements when installing your dependencies or are running with a different version than the one used to run composer.
> 
> You can force the dependency back to `v2` which is compatible with PHP 8.0 by requiring `"maennchen/zipstream-php": "^2.4"`.

Had this issue and your suggested solution helped me

**Comment by shaileshmmane** [comment] 2023-07-21 09:17
Installed PHP version 8.2.8.
I did composer require phpoffice/phpspreadsheet.

Getting error "syntax error, unexpected identifier "Closure", expecting variable "
VENDORPATH/maennchen/zipstream-php/src/ZipStream.php at line 111

**Comment by tanay-ictlayer** [comment] 2023-08-19 10:31
Install PHP VERSION >= 8.2

**Comment by oleibman** [comment] 2023-08-28 03:09
Closed as duplicate of #3615.

**Closed by oleibman** 2023-08-28 03:09 UTC

**Comment by MSayib** [comment] 2023-09-14 04:22
> ZipStream v3 requires PHP `^8.1` to work. I think you've ignored the plaform requirements when installing your dependencies or are running with a different version than the one used to run composer.
> 
> You can force the dependency back to `v2` which is compatible with PHP 8.0 by requiring `"maennchen/zipstream-php": "^2.4"`.

works like charm

**Comment by yashtomer** [comment] 2023-09-20 06:56
> ZipStream v3 requires PHP `^8.1` to work. I think you've ignored the plaform requirements when installing your dependencies or are running with a different version than the one used to run composer.
> 
> You can force the dependency back to `v2` which is compatible with PHP 8.0 by requiring `"maennchen/zipstream-php": "^2.4"`.

Thanks @maennchen !

works like a charm
