### ISSUE TITLE
Duration cell formatting is stripped as color formatting

### ISSUE THREAD

**Issue by ivankruchkoff** [PHPOffice/PhpSpreadsheet#446] opened 2018-03-30 20:26 UTC
This is:

```
- [X] a bug report
```

### What is the expected behavior?
Cell value is:
12:34
Formatting is:
[mm]:ss

Per: https://support.office.com/en-us/article/number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68 this is Elapsed time (minutes and seconds)

### What is the current behavior?
[mm] is stripped from formatting here: https://github.com/PHPOffice/PhpSpreadsheet/blob/ce4b864e017bb3f6a3a26627d91d13a4c140cb22/src/PhpSpreadsheet/Style/NumberFormat.php#L641

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
$value = 0.0087268518518519;
$format = '[mm]:ss';
NumberFormat::toFormattedString( $value, $format )
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.2.0
PHP 7.0.26-2+ubuntu14.04.1+deb.sury.org+2

### Sample File
[bug-report.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/1864699/bug-report.xlsx)
```php
$spreadsheet = $reader->load('bug-report.xlsx');
$spreadsheet->getActiveSheet()->getCell('A1')->getFormattedValue();
```

**Comment by PowerKiKi** [comment] 2018-04-14 05:33
This is a duplicate of #342. Please try to contribute over there if this is important to you.

**Closed by PowerKiKi** 2018-04-14 05:33 UTC
