### ISSUE TITLE
Error in the image size when generating PDF from Spreadsheet

### ISSUE THREAD

**Issue by brnyza** [PHPOffice/PhpSpreadsheet#1689] opened 2020-10-26 19:56 UTC
```
- [x ] a bug report
```

```
$objDrawing = new \PhpOffice\PhpSpreadsheet\Worksheet\MemoryDrawing();
$objDrawing->setImageResource(imagecreatefrompng($img_G5));
$objDrawing->setRenderingFunction(\PhpOffice\PhpSpreadsheet\Worksheet\MemoryDrawing::RENDERING_JPEG);
$objDrawing->setMimeType(\PhpOffice\PhpSpreadsheet\Worksheet\MemoryDrawing::MIMETYPE_DEFAULT);
$objDrawing->setCoordinates('B2');                      
$objDrawing->setWidthAndHeight(50, 50);
$objDrawing->getShadow()->setVisible(true);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());

$writer = new \PhpOffice\PhpSpreadsheet\Writer\Pdf\Dompdf($spreadsheet);
header('Content-Type: application/pdf');
header('Content-Disposition: attachment;filename='.$fileName);
header('Cache-Control: max-age=0');
$writer->save('php://output');
```

The image in PDF is not properly resized.
![error_Dompdf](https://user-images.githubusercontent.com/4684660/97221787-28210b00-17ac-11eb-8183-4dd7f85fc683.PNG)

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.4.10
PhpSpreadsheet 1.15

**Comment by lyoha** [comment] 2021-08-14 18:19
The problem is caused by incorrectly specified styles for the "img" tag in the PhpSpreadsheet/Writer/Html::writeImageInCell() method. For example, instead of "max-width: 100%" you should set "max-width: auto"

**Comment by oleibman** [comment] 2022-09-03 01:48
I am unable to duplicate this problem using samples/images/termsconditions.jpg as the source of the Memory Drawing. If you still have a problem with your file, can you please upload the file you used as `$img_G5` in your report so that I can investigate further.

**Comment by oleibman** [comment] 2023-01-25 04:37
Closing, no update in 4 months, no sample to work with.

**Closed by oleibman** 2023-01-25 04:37 UTC
