### ISSUE TITLE
Update allowed simple-cache version

### ISSUE THREAD

**Issue by tacman** [PHPOffice/PhpSpreadsheet#2468] opened 2021-12-26 14:08 UTC
This is:

```
- [ ] a bug report
- [ X ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

The package should run with the latest version of psr/simple-cache

### What is the current behavior?

Locked to version 1

### What are the steps to reproduce?

```bash
mkdir example && cd example
composer init
composer req psr/simple-cache
composer req phpoffice/phpspreadsheet
```

### Which versions of PhpSpreadsheet and PHP are affected?

Perhaps this isn't possible, since the latest version of PHP requires return types.  I've added the return types and will submit another PR if my tests pass.  Related: do we need to continue to support PHP 7.3?  It's EOL, bumping to 7.4 seems pretty common now.

**Comment by tacman** [comment] 2021-12-26 14:14
After playing around with this a bit, I realize it's not something I think I can fix.  Nor is it urgent, just seemed like one of those things that it's nice to be compatible with the latest versions of various dependencies.  Might be something for a next release.

**Comment by oleibman** [comment] 2021-12-27 19:17
Because of the use of `mixed` type, we can't migrate to a newer version of simple-cache until we no longer support anything below Php8. That will probably not happen for a year and a half still till Php7.4 support is no longer needed. Our documented support is for a PHP release until it reaches 6 months past EOL; so Php7.3 will be supported for around 6 months still. Closing PRs #2466 and #2467 now. Will leave this issue open for a bit but will probably close it in a few weeks as well.

**Comment by mmarton** [comment] 2021-12-30 13:15
You can still support simple-cache v2 with v1, it doesn't have return types, and if the user has php8+ than it install the simplecache v2 otherwise v1 version

**Comment by oleibman** [comment] 2021-12-31 00:39
V2 doesn't have return types, but it does have typed arguments, including some which are `mixed`, and therefore incompatible with Php7.

**Comment by mmarton** [comment] 2021-12-31 09:33
And that is why I suggested both. 
`"psr/simple-cache": "^1.0 || ^2.0"`
you don't need any code change and your users can have a newer one if they use php8+

**Comment by oleibman** [comment] 2021-12-31 16:56
It is certainly possible that I don't understand your suggestion. We have a source member Collection/Memory.php that implements CacheInterface. If we use V2, do methods declared inside that member not have to match the interface, e.g.
```php
public function get(string $key, mixed $default)
```
That's okay for customers on Php8, but not those on Php7.

Just out of curiosity, is there anything in particular that you are looking for in V2 that is not provided in V1?

**Comment by mmarton** [comment] 2022-01-03 11:05
Hi!

I'll try to explain better :)
the point of supporting both versions is to be more compatible with other libs (I don't know about any but there can be ones that only support simplecache 2+)

By having  `psr/simple-cache": "^1.0 || ^2.0` in the composer.json dependencies:
- for users on php7.4 and below composer will install the 1.0 version (because the 2.0 requires php8+)
- for users on php8.0 and above composer will install the 2.0 version

because of contravariance, you can "loose" the typehint from the interface, so the cache class could remain the same and it will be compatible with both simple-cache v1 and v2.

see:
http://sandbox.onlinephpfunctions.com/code/eba5005d8aadd09fc7744671fbf9b82ce6851c85

**Comment by oleibman** [comment] 2022-01-04 03:08
Thank you for the enlightening explanation. I can sort of intellectually understand why, but I still find it a bit mind-boggling that PHP7.2/3/4 can know that omitting a typehint "widens" a `mixed` typehint that they do no understand.

And yet, even though you have demonstrated that `mixed` will work with PHP7, simple-cache2 still lists PHP8 as a dependency requirement. And I think I see why. Let's look at line 34 of CacheInterface.php:
```php
public function set(string $key, mixed $value, null|int|\DateInterval $ttl = null);
```
We can get past the mixed, but we can't get past the typehint union.

So, as a practical matter, I have to test with multiple versions of PHP. All of those work with simple-cache1; not all of them work with simple-cache 2. I do have sympathy for "compatibility with other libs"; but that seems like a theoretical problem, and the problem I face is a practical one - practicality wins, at least for the moment.

**Comment by kwasnicki** [comment] 2022-01-06 23:49
Hi, just throwing my 2cents in here because I ended up here exactly because of the "other libs" problem.  My app is using both phpspreadsheet and phpfastcache package which recently released a new major version, 9, that requires psr/simple-cache ^2 so now I'm having upgrade conflicts. 

However my upgrade attempts right now are only for dev experiments where I have php8 because my prod server is still on php7,  so I don't have an imminent need to upgrade.   Just wanting to note that when I do want to upgrade this conflict could be an issue, so not totally theoretical, and if making the "^1 || ^2" composer change noted above is possible without breaking php7 it might be something to consider?  Thanks!

**Comment by MaximilianKresse** [comment] 2022-02-01 10:41
> We can get past the mixed, but we can't get past the typehint union.
> 
> So, as a practical matter, I have to test with multiple versions of PHP. All of those work with simple-cache1; not all of them work with simple-cache 2. I do have sympathy for "compatibility with other libs"; but that seems like a theoretical problem, and the problem I face is a practical one - practicality wins, at least for the moment.

I think there is a general misunderstanding. The only reason for simple-cache 2.0 to exist is to be a bridge between version 1 and 3. Version 2 and 3 were released at the same day. Creating a version bridge like this is possible because of the type widening of [php >=7.2](https://wiki.php.net/rfc/parameter-no-type-variance). Version 2 is without return types so there are no backward incompatible changes and any parameter type can just be widened. Here a small live demonstration of type widening: https://3v4l.org/asr8j

There are in total three groups of combinations possible with "^1.0 || ^2.0":
1. PHP 7.3 and 7.4 will always only use simple-cache ^1.0, because of the php version constraint of simple-cache 2.0 (>=8.0)
2. PHP >= 8.0 projects will by default use simple-cache ^2.0
3. PHP >= 8.0 projects with other dependencies to simple-cache ^1.0 will still use simple-cache ^1.0

None of this combinations will result in any errors or problems with this interface. It would only be a problem **IF** psr/simple-cache 2.0 would allow php versions <= 7.2. Only then the interface wouldn't be fulfilled.

> So, as a practical matter, I have to test with multiple versions of PHP.

At the moment you already "just" test with the highest possible versions of your dependencies in your automated tests. Sure you could test every possible combination - but no sane person would do this 🤣 The only case which wouldn't be catched in your current test cases is variation 3 but there is no reason why it should fail.

I really hope you take a second thought about this. As it restricts us unnecessary in our dependencies.

**Comment by oleibman** [comment] 2022-02-04 15:18
I am not an expert on Composer, so take what I have to say here with a grain of salt.

As noted above, it is *not* true that "Version 2 is without return types so there are no backward incompatible changes". The addition of typehint unions to some parameters in Version 2 is backward incompatible.

It is also not precisely true that I "test with the highest possible versions of your dependencies"; I test with whatever is specified in composer.lock, which I agree will often be the highest possible version.

So, here's my problem. At the moment, I can install the package with Composer using whatever version of PHP I wish, and the resulting code will work will work with all versions of PHP which we support. With your suggested change, if I use Composer with PHP8, the resulting code will fail if I try to execute it with PHP7.3/7.4 because of the typehint unions. I assume this will not be a problem for you because you have measures to prevent commingling of PHP releases. However, I am far from sure that this will not cause problems for other users.

If simple-cache V2 was intended as a compatibility bridge, it doesn't seem to satisfy that intention. I think if it were to use `mixed` rather than the typehint unions, and used a requirement of PHP7.3+ or PHP8, we could consider it (but that might, of course, cause problems for its users).

**Comment by MaximilianKresse** [comment] 2022-02-04 15:54
Thank you for your answer.

> As noted above, it is _not_ true that "Version 2 is without return types so there are no backward incompatible changes". The addition of typehint unions to some parameters in Version 2 is backward incompatible.

There is not a single return type in the CacheInterface 2.0.0: https://github.com/php-fig/simple-cache/blob/2.0.0/src/CacheInterface.php

The usage of typehint unions doesn't matter because of type widening. The type of a parameter is allowed to be widened by its implementation. The interface of 2.0 says ```public function set(string $key, mixed $value, null|int|\DateInterval $ttl = null);``` and your implementation is still allowed to look the same like now ```public function set($key, $value, $ttl = null);``` all parameter types are widened by "everything is allowed". 
Additionally like listed above PHP7.3 and 7.4 will NEVER use the CacheInterface ^2.0 only ^1.0. 
 
> So, here's my problem. At the moment, I can install the package with Composer using whatever version of PHP I wish, and the resulting code will work will work with all versions of PHP which we support.

This could be just a coincidence - composer will not help you with this. It will only ensure that your currently used PHP version is compatible with everything.

> With your suggested change, if I use Composer with PHP8, the resulting code will fail if I try to execute it with PHP7.3/7.4 because of the typehint unions. I assume this will not be a problem for you because you have measures to prevent commingling of PHP releases. However, I am far from sure that this will not cause problems for other users.

Yes! This is correct. But this easiest way to walk around this problem is to simply just use php 7.3 for composer install/update and everything will be exactly like now.

> If simple-cache V2 was intended as a compatibility bridge, it doesn't seem to satisfy that intention.

 It really does. Try it yourself if you don't believe us :-)

> I think if it were to use `mixed` rather than the typehint unions, and used a requirement of PHP7.3+ or PHP8, we could consider it (but that might, of course, cause problems for its users).

The typehint unions will never be used by PHP 7.3.

**Closed** 2022-03-19 11:43 UTC

**Comment by MarkBaker** [comment] 2022-04-26 19:12
@kjmartens Because of the use of mixed type in simple-cache 3.0, we can't match our implementation to the simple-cache 3.0 interface until we support only PHP8 and above. The only way we could work it would be to have two version-specific implementations, and a run-time identifier that chose which one to use.

**Comment by MaximilianKresse** [comment] 2022-04-26 20:47
> @oleibman, I see that the change has been made to support both 1.0 and 2.0. As @MaximilianKresse mentions, the way dependencies are chosen, this change will allow for much better compatibility between other dependency requirements and PHP versions. I'm wondering if you would be willing to update `phpoffice/phpspreadsheet` to also support `^3.0` of `psr/simple-cache`.
> 
> We have a plugin for [Craft CMS](https://github.com/craftcms/cms) that calls a dependency that ultimately can load `3.0` of `psr/simple-cache` . Our use of `phpoffice/phpspreadsheet` may potentially run into installation errors (under certain circumstances) because this library doesn't also support the `^3.0` version of `psr/simple-cache`.
> 
> So:
> 
> ```
> "psr/simple-cache": "^1.0 || ^2.0 || ^3.0"
> ```
> 
> As @MaximilianKresse mentions, 3.0 would only ever be chosen by Composer if the server environment was compatible with it. Sorry to comment on an older thread, but I noticed this was just added and released 2 days ago. 🙂

You mixed something up there. PhpSpreadsheet cannot do this because this will be a BC. The library which uses ^3.0 has to add "^2.0 || ^3.0".
