### ISSUE TITLE
cannot work setCellValue using any Japanease charactors

### ISSUE THREAD

**Issue by gsjp1919** [PHPOffice/PhpSpreadsheet#551] opened 2018-06-15 06:17 UTC
I would show some screen shot of my problem!
"setCellValue" do not work by using any Japanease charactors.

I tryed to use those Japanease charactors "日本語テスト"
"日本語テスト" is not worked.
"English Test" is worked.

I already checked encode utf-8

```
Array
(
    [internal_encoding] => UTF-8
    [http_output] => UTF-8
    [http_output_conv_mimetypes] => ^(text/|application/xhtml\+xml)
    [func_overload] => 0
    [func_overload_list] => no overload
    [mail_charset] => UTF-8
    [mail_header_encoding] => BASE64
    [mail_body_encoding] => BASE64
    [illegal_chars] => 0
    [encoding_translation] => Off
    [language] => neutral
    [detect_order] => Array
        (
            [0] => UTF-8
        )

    [substitute_character] => 63
    [strict_detection] => Off
)
```
Please help and give some solutions!

My Development ：
Centos6.7
PHP Version 5.6.4
Server API | Apache 2.0 Handler
Excel Microsoft Office Professional Plus 2010 version 14.0.7208.5000(32bit)

```
<?php
ini_set('default_charset', '');
mb_http_output('pass');

$ary[] = "UTF-8";
mb_detect_order($ary);

echo "<pre>mb_get_info():\n";
print_r(mb_get_info());
echo "</pre>\n";


require '/home/chicago/vendor/autoload.php';

$str = '日本語テスト';
$str2 = 'English Test';
$str3 = '="日本語テスト"';
?>
<!doctype html>
<html>
    <head>
        <meta charset = "utf-8">
        <title></title>

    </head>
    <body>
        <?php
        //My Development UTF-8
        echo "mb_detect_encoding:" . mb_detect_encoding($str) . "<br>";
        //My Development UTF-8
        echo "mb_detect_encoding:" . mb_detect_encoding($str2) . "<br>";
        //My Development UTF-8
        echo "mb_detect_encoding:" . mb_detect_encoding($str3) . "<br>";
        ?>
    </body>
</html>

<?php

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

$sheet
        ->getStyle("A1:Z2500")
        ->getNumberFormat()
        ->setFormatCode(PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_TEXT);


//Just use "setCellValue"　'日本語テスト' 
$sheet->setCellValue('A1', $str);

//Just use "setCellValue"　'English Test'
$sheet->setCellValue('A2', $str2);

//Just use "setCellValue"　'="日本語テスト"'
$sheet->setCellValue('A3', $str3);
![image04](https://user-images.githubusercontent.com/40282343/41452442-0379baa2-70ad-11e8-9b32-262d6367cc0f.png)

$writer = new Xlsx($spreadsheet);
$writer->save('test.xlsx');

?>
```
![image04](https://user-images.githubusercontent.com/40282343/41453030-357512de-70af-11e8-848d-413d4a9569c6.png)

thank you for your help

**Comment by PowerKiKi** [comment] 2018-06-15 07:07
Duplicate of #550

**Closed by PowerKiKi** 2018-06-15 07:07 UTC
