### ISSUE TITLE
When will the hotfix made post 1.3.0 be pushed to the master branch (ie. composer)

### ISSUE THREAD

**Issue by alexscott64** [PHPOffice/PhpSpreadsheet#547] opened 2018-06-11 22:06 UTC
Unfortunately, I can't ask this on Stackoverflow and this isn't an issue that fits into a template. There is a bug in 1.3.0 that is breaking our site. It was fixed though, however composer has no update (since it's referencing 1.3.0). My question is, how long does it usually take to push a fix for a major release out to composer? Right now we have had to manually modify the affected file. Otherwise, is there something else we can do?

**Comment by PowerKiKi** [comment] 2018-06-12 06:11
Duplicate of #546, #545 and #521 latest comments. Please continue the discussion over there.

**Closed by PowerKiKi** 2018-06-12 06:11 UTC

**Comment by PowerKiKi** [comment] 2018-06-12 13:44
It's been released as [1.3.1](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.3.1)
