### ISSUE TITLE
PHP Warnings when saving Excel with formulas constructed from IF, ISNA, and VLOOKUP 

### ISSUE THREAD

**Issue by mjan4175** [PHPOffice/PhpSpreadsheet#2745] opened 2022-04-12 18:06 UTC
This is:

```
- [x] a bug report

```

### What is the expected behavior?
PhpSpreadsheet correctly opens and saves the attached file.

### What is the current behavior?
When saving the file, the following PHP warning occurs:
PHP Warning:  end() expects parameter 1 to be array, bool given in Calculation/Calculation.php on line 4417

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$xlsxFilename = '/path/to/attached/vlookup.xlsx';
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($xlsxFilename);
$spreadsheet = $reader->load($xlsxFilename);

// add code that show the issue here...
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->save($xlsxFilename);

```

[vlookup.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8475411/vlookup.xlsx)

### Which versions of PhpSpreadsheet and PHP are affected?
Tested in PHP 7.4.
The master branch is affected, version 1.22.0 is OK.

**Comment by MarkBaker** [comment] 2022-04-12 19:43
There is a known problem with empty values in an `IF()` when branch pruning is enabled for lazy evaluation of the if, (the default).

Either disable pre-calculation before saving the file (not always an option if you have autosize columns); or disable branch pruning using
```
$calculationEngine = Calculation::getInstance($spreadsheet);
$calculationEngine->disableBranchPruning();
```

**Comment by mjan4175** [comment] 2022-04-13 05:22
Will this issue be corrected before releasing a new version, or should I sanitize my code before upgrading from 1.22.0 by disabling branch pruning whenever an unknown spreadsheet is opened?

The issue affects not only saving of the file, it occurs also when calling `getCalculatedValue` on cell with such formula.

**Comment by MarkBaker** [comment] 2022-04-13 06:53
The issue is unlikely to be resolved before the next release... I've done some work on isolating the logic of branch pruning from the main body of the calculation engine to try and make it easier to identify the cause of the issue; but it's a complicated piece of code.
It affects all Excel calculations, whether requested directly via method calls like `geCalculatedValue()`, `geFormatttedValue()`  and `toArray()`, and when calling `save()` with preCalculatedValues enabled, or where calculation needs executing to calculate autofit column widths.
Fortunately most people don't use IF() in formula calculations with empty arguments in their spreadsheets (the issue doesn't occur with non-empty arguments).

So yes, I would recommend disabling branch pruning until I've found a solution to the issue. This makes calculation slower if the arguments for the IF() include nested function calls; but doesn't trigger the error.

**Comment by MarkBaker** [comment] 2022-04-13 19:12
[PR #2748](https://github.com/PHPOffice/PhpSpreadsheet/pull/2748), just merged to `master` should mean that you don't need to disable branch pruning

**Comment by mjan4175** [comment] 2022-04-14 05:22
Thanks for a prompt reaction. Your fix is works ok.

**Closed** 2022-05-08 18:16 UTC
