### ISSUE TITLE
Allow newer psr/simple-cache version

### ISSUE THREAD

**Issue by MrReeds** [PHPOffice/PhpSpreadsheet#2659] opened 2022-03-07 17:29 UTC
This is:

```
- [ ] a bug report
- [ X ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
phpoffice/phpspreadsheet  1.22.0  requires  psr/simple-cache (^1.0|^2.0|^3.0)

### What is the current behavior?
phpoffice/phpspreadsheet  1.22.0  requires  psr/simple-cache (^1.0)

### What are the steps to reproduce?
composer depends psr/simple-cache

### Which versions of PhpSpreadsheet and PHP are affected?
1.22.0

**Comment by MarkBaker** [comment] 2022-03-07 18:48
Duplicate of https://github.com/PHPOffice/PhpSpreadsheet/issues/2468

**Closed by MarkBaker** 2022-03-07 18:48 UTC
Labels: duplicate
