### ISSUE TITLE
PHP spreadsheet not formatting cell correctly

### ISSUE THREAD

**Issue by garrettgjb** [PHPOffice/PhpSpreadsheet#343] opened 2018-01-20 15:21 UTC
Sorry reopening because I posted some invalid php and the old issue was closed.

This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I expect for the column containing "Duration" should come in as "mm" format as defined in excel. Meaning it should look like an integer as you see when you are in excel.
<img width="134" alt="screen shot 2018-01-19 at 9 07 59 pm" src="https://user-images.githubusercontent.com/549725/35180085-f750d49a-fd5c-11e7-8892-ee3e9b0f83a3.png">

The column subtracts one date from another date.
I.e.

2018-01-22 02:00:00 PM - 2018-01-22 01:00:00 PM

We format is as [mm] so it would be 60.

I think what is happening is this library doesn't know how to do binary operations with dates. If you multiple the decimal number by 1440 you get the correct number. Or it isn't formatting it correctly.

### What is the current behavior?
Duration column comes in as a decimal in the php code.
<img width="267" alt="screen shot 2018-01-19 at 9 00 56 pm" src="https://user-images.githubusercontent.com/549725/35180048-05b7b40a-fd5c-11e7-8719-1a153176c1f8.png">

### What are the steps to reproduce?
Import the following file with phpspreadsheet:
[importtest-phpspreadsheet.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/1648584/importtest-phpspreadsheet.xlsx)

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

	require __DIR__ . '/vendor/autoload.php';

	$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();

	$file="importtest-phpspreadsheet.xlsx";
	$spreadsheet = $reader->load($file);
	$worksheet = $spreadsheet->getActiveSheet();

	echo "Should be 60";
	echo "\nActual: " . ($spreadsheet->getActiveSheet()->getCell('K2')->getFormattedValue());
	echo "\nFinished";
```

**Current output:**
Should be 60
Actual: 0.041666666671517

**Expected output:**
Should be 60
Actual: 60

If you open the spreadsheet in excel, cell K2 is in fact 60.

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 5.6, Latest phpspreadsheet from composer

**Comment by PowerKiKi** [comment] 2018-01-21 04:52
Duplicate of #342

**Closed by PowerKiKi** 2018-01-21 04:52 UTC
