### ISSUE TITLE
Problem with mbstring.func_overload 2

### ISSUE THREAD

**Issue by gserrg** [PHPOffice/PhpSpreadsheet#1658] opened 2020-09-24 17:25 UTC
Hello. My config:
* php 7.2
* mbstring.func_overload 2
* phpoffice / phpspreadsheet 1.13.0 (or newer)
Incorrect xlsx is generated. If you change func_overload to 0 or roll back to the previous version of phpspreadsheet, then the problem disappears.

```json
{
    "require": {
        "phpoffice/phpspreadsheet": "1.13.x"
    }
}
```
[composer.lock.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/5278037/composer.lock.zip)

```php
<?php
require_once('vendor/autoload.php');

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'текст');

$writer = new Xlsx($spreadsheet);
$writer->save('file.xlsx');
```

[file_bad_mbstring.func_overload_2.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/5278030/file_bad_mbstring.func_overload_2.xlsx)
[file_good_mbstring.func_overload_0.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/5278032/file_good_mbstring.func_overload_0.xlsx)

**Comment by dimanimda** [comment] 2020-10-25 12:07
Thank you! I have same issue.

**Comment by gserrg** [comment] 2020-12-25 14:49
it's easier not to use the library than to communicate with bots

**Comment by noopple** [comment] 2021-04-05 16:20
@gserrg https://github.com/PHPOffice/PhpSpreadsheet/issues/1951

**Comment by MarkBaker** [comment] 2021-04-28 12:44
Duplicate of [#1951](https://github.com/PHPOffice/PhpSpreadsheet/issues/1951)

**Closed by MarkBaker** 2021-04-28 12:44 UTC
