### ISSUE TITLE
setTextRotation is not displayed correctly when xlsx file opened with MacBook Numbers

### ISSUE THREAD

**Issue by edvinasmedicus** [PHPOffice/PhpSpreadsheet#3359] opened 2023-02-11 10:51 UTC
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
![0076D41F-57D8-4C47-847D-2F8F427BEEB8](https://user-images.githubusercontent.com/93519633/218253830-e5a3652d-f42a-4bc0-82c5-7773382f133e.jpeg)

### What is the current behavior?

![92B06B29-3641-449F-8016-D47822733C40_4_5005_c](https://user-images.githubusercontent.com/93519633/218253899-8c3b1ceb-2c68-4a37-a37d-a22ea6882944.jpeg)

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$worksheet = new \PhpOffice\PhpSpreadsheet\Worksheet\Worksheet($spreadsheet, 'Test Text Rotation');
$worksheet->setCellValue([1, 1], 'Total');
$style = $worksheet->getStyle([1, 1, 1, 1]);

// Set the text rotation to 90 degrees
$style->getAlignment()->setTextRotation(90);

```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Affected only when opened in MacBook "Numbers"

### Which versions of PhpSpreadsheet and PHP are affected? 
1.27.1

**Comment by MarkBaker** [comment] 2023-02-11 15:06
Does Numbers show correct text rotation when reading a file generated using MS Excel? Not all spreadsheet programs can read every aspect of the xlsx format, so it's possible that the problem here is Numbers rather than PhpSpreadsheet; and if Numbers can't read text rotation, then there isn't much that we can do about it

**Comment by oleibman** [comment] 2023-08-28 06:12
Closing, no update in 6 months, no reason to believe that the problem is with PhpSpreadsheet rather than Numbers.

**Closed by oleibman** 2023-08-28 06:12 UTC
