### ISSUE TITLE
PHP-CACHE / filesystem-adapter does not support dashes in the key/file name. PSR-6

### ISSUE THREAD

**Issue by inet2800** [PHPOffice/PhpSpreadsheet#366] opened 2018-02-09 00:22 UTC
This is: BUG.

PHP-CACHE/filesystem-adapter checks the key/file name to conform to PSR-6. The current file names use dashes which are not allowed under PSR-6. Please see below. Suggest using a period, (.).

"Key - A string of at least one character that uniquely identifies a
cached item. Implementing libraries MUST support keys consisting of the
characters A-Z, a-z, 0-9, _, and . in any order in UTF-8 encoding and a
length of up to 64 characters. Implementing libraries MAY support additional
characters and encodings or longer lengths, but must support at least that
minimum. Libraries are responsible for their own escaping of key strings
as appropriate, but MUST be able to return the original unmodified key string.
The following characters are reserved for future extensions and MUST NOT be
supported by implementing libraries: {}()/@"
```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

**Comment by PowerKiKi** [comment] 2018-02-09 00:59
Duplicate of #354

**Closed by PowerKiKi** 2018-02-09 00:59 UTC
