### ISSUE TITLE
Writer yielding corrupted output spreadsheet given non-corrupted input spreadsheet

### ISSUE THREAD

**Issue by ornithophile** [PHPOffice/PhpSpreadsheet#2401] opened 2021-11-18 00:24 UTC
This is:

```
- [X] a bug report
```

### What is the expected behavior?

To open the spreadsheet, fill in the cell values, and produce a usable spreadsheet.

### What is the current behavior?

Excel indicates that the spreadsheet is corrupted; the input spreadsheet is not.

### What are the steps to reproduce?

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$xlsxPayload = [
  'C2' => 'Enphase IQ7-60-2-US',
  'C3' => 'Hanwha Q CELLS Q.PEAK DUO BLK-G6+ 340',
  'C12' => '123 fake st',
  'C13' => 'Fake, CA 99999',
  'C14' => 'Fake Person',
  'C15' => '6612342324',
  'C16' => '11/17/2021',
  'C40' => '11/17/2021',
  'C20' => 16,
  'C46' => 206,
  'C52' => 21,
  'C21' => 0,
  'C47' => 0,
  'C53' => 0,
  'C22' => 0,
  'C48' => 0,
  'C54' => 0,
  'C23' => 0,
  'C49' => 0,
  'C55' => 0,
  'C24' => 0,
  'C50' => 0,
  'C56' => 0,
];

try {
  $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
  $spreadsheet = $reader->load("Design_Form.xlsx");
  $sheet = $spreadsheet->getSheetByName('Inputs');
  foreach ($xlsxPayload as $cell => $value)
    $sheet->setCellValue($cell, $value);
  $writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
  $writer->save("Output.xlsx");
} catch (\PhpOffice\PhpSpreadsheet\Reader\Exception $e) {
  echo $e->getMessage();
} catch (\PhpOffice\PhpSpreadsheet\Writer\Exception $e) {
  echo $e->getMessage();
}
?>

```

### Which versions of PhpSpreadsheet and PHP are affected?
1.19 / 7.4

**Comment by ornithophile** [comment] 2021-11-18 00:25
![image](https://user-images.githubusercontent.com/47016563/142309754-376cf324-36b3-4faa-b4c1-12e726079939.png)

![image](https://user-images.githubusercontent.com/47016563/142309898-ba9ba598-adcd-411c-8906-26993813d951.png)

**Comment by ornithophile** [comment] 2021-11-18 00:25
[Design_Form.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7558873/Design_Form.xlsx)
[Output.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7558874/Output.xlsx)

**Comment by oleibman** [comment] 2021-11-18 01:28
Closing as duplicate of #2368. File contains Data Validations. Fix is available in master.

**Closed by oleibman** 2021-11-18 01:28 UTC
