### ISSUE TITLE
result of a formula is printed over the previous one in Excel 2007

### ISSUE THREAD

**Issue by felix-the-real-cat** [PHPOffice/PhpSpreadsheet#284] opened 2017-12-05 10:33 UTC
This is:

- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
The cell content should firstly be cleared and then the new result 'inserted' in the cell.

### What is the current behavior?
In excel 2007 it looks like all the results of the formula are are stacked ! The content is not erased before the new result is printed.

### What are the steps to reproduce?
create a file with phpspreadsheet, save it, load it and save it again into a new file; **then change the value of cell E3 or E4** to trigger a new calculation of cell E6. The new result is stacked over the previous one until you scroll up and down to refresh the screen (see screenshot available in the stackoverflow link provided below).

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

The source of the problem is identified in the following post (see EDIT 1):
https://stackoverflow.com/questions/47630995/phpexcel-1-8-result-of-a-formula-is-printed-over-the-previous-one-in-excel-200

### Which versions of PhpSpreadsheet and PHP are affected?
PHPExcel 1.8.1 (last release) & PHPSpreadsheet-devel (as of 2017-12-04)
PHP v 7.1.7
Document opened with Excel 2007

**Comment by PowerKiKi** [comment] 2017-12-05 11:53
Duplicate of #283. Please don't duplicate issues, instead complete the original discussion with more information.

**Closed by PowerKiKi** 2017-12-05 11:53 UTC
