### ISSUE TITLE
Exclude samples and docs from Composer package

### ISSUE THREAD

**Issue by FinesseRus** [PHPOffice/PhpSpreadsheet#166] opened 2017-05-31 06:59 UTC
The `samples` and `docs` directories weight really much (7.1MB, 59%) and not required in a production.

I suggest to set this repository up a way to make Composer not to download this files.

**Comment by PowerKiKi** [comment] 2017-05-31 08:03
Duplicate of #139

**Closed by PowerKiKi** 2017-05-31 08:03 UTC
