### ISSUE TITLE
Copying File with Checkboxes Produces Corrupt Result

### ISSUE THREAD

**Issue by marcelWireless** [PHPOffice/PhpSpreadsheet#2661] opened 2022-03-08 14:05 UTC
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
create file or write without errors

### What is the current behavior?
error when opening created file 
Repaired Records: Feature formatting (DXFs) from /xl/styles.xml part (Styles)
![image-20220307-093628](https://user-images.githubusercontent.com/101175161/157252671-999f4388-026e-47b1-b5f6-78d7eaf9254f.png)

[corrupted_file.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8206813/corrupted_file.xlsx)

### What are the steps to reproduce?
load the template file and then write data into it and save as new file and then try to open.

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

please see curupted file with the issue

```php
<?php

require __DIR__ . '/

vendor/autoload.php';


// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

### Which versions of PhpSpreadsheet a
nd PHP are affected?
1.22.0

#### Template file
[template.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8206781/o2_api_new_request_template.xlsx)

**Comment by marcelWireless** [comment] 2022-03-08 14:06
When i deleted on template all the conditional formatting the the file was created without any issues but that is not the way it should work. We need those conditional formatting when creating file from template.
thanks

**Comment by oleibman** [comment] 2022-03-08 15:11
The problem is not with conditional formatting, it is with the use of form fields, namely checkboxes. I think that if you are able to test against PR #2455, you will find that you can load the template and save it correctly as an Xlsx spreadsheet. Unfortunately, that PR does not yet solve enough related problems to make it out of draft status, but the fact that it helps here is an argument in favor of proceeding.

**Comment by marcelWireless** [comment] 2022-03-08 15:33
ohh ok but that PR is not release yet if I understand correctly right?
Do you know when will that fix be release?

**Comment by oleibman** [comment] 2022-03-08 16:26
Correct, the PR is not yet merged. I don't expect it to be merged all that soon. I am wrestling with the question of "If this doesn't fix all related problems, is it nevertheless good enough to install?" Your issue is a mark in its favor.

**Closed** 2022-12-28 16:01 UTC
Labels: form controls
