### ISSUE TITLE
Support saving to handles in all writers

### ISSUE THREAD

**Issue by jnvsor** [PHPOffice/PhpSpreadsheet#427] opened 2018-03-16 17:18 UTC
This is:

- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?

Writing a spreadsheet to a `php://memory` handle (Or any handle for that matter) would be useful for responding to requests using something like HttpFoundation instead of writing directly to stdout or a temp file. (See also #28)

### What is the current behavior?

Some writers don't support handles, and typically throw a WriterException. The Xlsx writer is a good example.

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$handle = fopen('php://memory', 'w+');
$writer->save($handle);
```

### Which versions of PhpSpreadsheet and PHP are affected?
All

**Comment by PowerKiKi** [comment] 2018-04-01 22:47
I believe this is an exact duplicate of #28, that you mentioned yourself. And my comments from there still stand.

Feel free to contribute to the discussion over there, or better yet suggest a PR for it.

**Closed by PowerKiKi** 2018-04-01 22:47 UTC

**Comment by jnvsor** [comment] 2018-04-01 23:18
It's not a duplicate: #28 wants to get a resource from the save method, I want to be able to pass one to it.

This doesn't require a change in method signature, and is already implemented in some writers (But inconsistently, hence this bug)

For example, `Writer\Xls` [calls](https://github.com/PHPOffice/PhpSpreadsheet/blob/5f036591cdc1a4f848edd83db8666bcf20874c78/src/PhpSpreadsheet/Writer/Xls.php#L224) [OLE/PPS/Root::save](https://github.com/PHPOffice/PhpSpreadsheet/blob/8380fb3ad28242093c18d0baa9b7e67fb429ea84/src/PhpSpreadsheet/Writer/Xlsx.php#L173) which [checks if the passed `$filename` is a resource](https://github.com/PHPOffice/PhpSpreadsheet/blob/8380fb3ad28242093c18d0baa9b7e67fb429ea84/src/PhpSpreadsheet/Writer/Xlsx.php#L181) and uses it instead, while `Writer\Xlsx` only accepts a string.
