### ISSUE TITLE
Update all 3rd-party modules to latest versions

### ISSUE THREAD

**Issue by Quix0r** [PHPOffice/PhpSpreadsheet#124] opened 2017-03-27 16:48 UTC
If I run `composer update` it gives me some updated packages:
````
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 16 updates, 0 removals
  - Updating squizlabs/php_codesniffer (2.8.0 => 2.8.1) Loading from cache
  - Updating symfony/yaml (v3.2.4 => v3.2.6) Downloading: 100%
  - Updating phpunit/php-timer (1.0.8 => 1.0.9) Loading from cache
  - Updating sebastian/code-unit-reverse-lookup (1.0.0 => 1.0.1) Loading from cache
  - Updating phpunit/php-token-stream (1.4.10 => 1.4.11) Loading from cache
  - Updating phpunit/php-code-coverage (4.0.6 => 4.0.7) Loading from cache
  - Updating phpspec/prophecy (v1.6.2 => v1.7.0) Loading from cache
  - Updating phpunit/phpunit (5.7.14 => 5.7.17) Downloading: 100%
  - Updating symfony/stopwatch (v3.2.4 => v3.2.6) Downloading: 100%
  - Updating symfony/process (v3.2.4 => v3.2.6) Downloading: 100%
  - Installing symfony/polyfill-xml (v1.3.0) Loading from cache
  - Updating symfony/finder (v3.2.4 => v3.2.6) Downloading: 100%
  - Updating symfony/filesystem (v3.2.4 => v3.2.6) Downloading: 100%
  - Updating symfony/event-dispatcher (v3.2.4 => v3.2.6) Downloading: 100%
  - Updating symfony/debug (v3.2.4 => v3.2.6) Downloading: 100%
  - Updating symfony/console (v3.2.4 => v3.2.6) Downloading: 100%
  - Updating friendsofphp/php-cs-fixer (v2.1.0 => v2.1.2) Downloading: 100%
Writing lock file
Generating autoload files
$
````
Please consider updating them and let me know.

**Comment by PowerKiKi** [comment] 2017-03-28 09:48
I am closing this as it is not really helpful. It is not a bug report, nor a contribution for improvement. Moreover while we try to stay up to date, packages are bound to be out of date rather quickly.

Next time either provide a PR that directly solve your concern, or only submit a bug report that explain what in great details what is broken and why it should be fixed.

**Closed by PowerKiKi** 2017-03-28 09:48 UTC

**Comment by Quix0r** [comment] 2017-03-29 07:07
How much chance do I have to get that PR through quickly (so I don't need to rebase + force-push always)? That is why I have only suggested here to stay up-to-date (and with `composer update` very easy to do). This keeps your library more error-free and more stable than with out-dated libraries (I guess you have choosen stable branches in `composer.json`).
