### ISSUE TITLE
Unreadable content if some sheet has a long text for every cells.

### ISSUE THREAD

**Issue by christophervistal25** [PHPOffice/PhpSpreadsheet#3292] opened 2023-01-12 06:13 UTC
This is:

```
- [ x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ x ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?

![First](https://user-images.githubusercontent.com/46248327/211991167-c6a0e55f-397e-42e7-a2a2-9df1743798a6.PNG)

![Second](https://user-images.githubusercontent.com/46248327/211991183-8028b409-9aaf-4095-996a-4dd942003f84.PNG)

Now if I remove some content or record in learning and development in our web application this is the result.
as you can see is print/displayed perfectly.
![Third](https://user-images.githubusercontent.com/46248327/211991187-25d99f49-d15b-4faf-a092-b606867998c7.PNG)

**Comment by oleibman** [comment] 2023-01-12 07:12
This might be a duplicate of issue #2884, with additional comments in unimplemented closed PR #2913. I can't really tell if it's the same problem without seeing your file. However, before requesting that, it would be useful to know if your spreadsheet opens correctly in Libre Office Calc. Excel has a hard limit of 32,767 characters in a cell, and, for the possible duplicate issue, the problem seemed to be a bug with Excel itself. Libre Office does not have that limit, which is why it is useful to see if it can handle your file. If it can, it would be useful to know the length of the "long text" string, e.g. by using `=LEN(longtextcell)` in another cell.

**Comment by christophervistal25** [comment] 2023-01-12 09:55
I study and reproduce the bug If the cell content has a symbol like "-" or "/" or "'"
it breaks the format

**Comment by christophervistal25** [comment] 2023-01-12 09:55
I also examined the length of each cells it ranged from 30-200 characters only

**Comment by oleibman** [comment] 2023-01-12 16:44
Okay then, whatever it is is a different problem. I would still need to see your workbook. If you are concerned about loading it publicly, I can open a private repository to which you can upload it.

**Comment by sdsitu061960** [comment] 2023-01-15 04:31
Sorry for late response but I've already solved the issue using LibreOffice headless by converting the xls into xlsx.

**Comment by oleibman** [comment] 2023-08-28 06:15
Closing, no update in 8 months, no sample file exhibiting this bug to debug with.

**Closed by oleibman** 2023-08-28 06:15 UTC
