### ISSUE TITLE
Undefined index $ error when excel has exists filter 

### ISSUE THREAD

**Issue by lxShaDoWxl** [PHPOffice/PhpSpreadsheet#1169] opened 2019-09-23 05:44 UTC
This is:
- [x] a bug report

### What is the expected behavior?
Correct read excel file

### What is the current behavior?
return error

### What are the steps to reproduce?

If added filter in google spreadsheets and download file
https://docs.google.com/spreadsheets/d/1qQhpDrSh9VGqNqrl22nDE7UQBaOL2NrIucq7vUkto_c/edit?usp=sharing
to error
`PHP Notice:  Undefined index: $ in vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php on line 282`

example code

```<?php

use PhpOffice\PhpSpreadsheet\IOFactory;

require __DIR__.'/vendor/autoload.php';

$path = __DIR__.'/test2.xlsx';
/** @var \PhpOffice\PhpSpreadsheet\Reader\Xlsx $reader */
$reader = IOFactory::createReaderForFile($path);
$phpSpreadsheet = $reader->load($path);
$sheet = $phpSpreadsheet->getSheet(1);
```

### Which versions of PhpSpreadsheet and PHP are affected?
phpspreadsheet 1.9.0
php 7.1.30

**Comment by lxShaDoWxl** [comment] 2019-11-22 11:54
Bot: this is still an issue.

**Comment by CharlyPoppins** [comment] 2019-12-16 16:55
#https://github.com/PHPOffice/PhpSpreadsheet/issues/976

**Comment by CharlyPoppins** [comment] 2019-12-16 16:55
Duplicate of #https://github.com/PHPOffice/PhpSpreadsheet/issues/976

**Comment by astronati** [comment] 2020-01-15 15:36
IMHO It should be fixed by https://github.com/PHPOffice/PhpSpreadsheet/pull/1326

**Comment by lxShaDoWxl** [comment] 2020-03-20 05:34
Bot: this is still an issue.

**Closed** 2020-03-27 06:15 UTC
