### ISSUE TITLE
documentation is out of sync

### ISSUE THREAD

**Issue by marcelloh** [PHPOffice/PhpSpreadsheet#216] opened 2017-09-07 08:53 UTC
Go to
https://phpspreadsheet.readthedocs.io/en/develop/topics/reading-files/

read the paragraph:
Loading a Spreadsheet File

notice:
See Examples/Reader/exampleReader01.php for a working example of this code.

Where is this example?

**Comment by PowerKiKi** [comment] 2017-09-08 18:48
Duplicate of #17

**Closed by PowerKiKi** 2017-09-08 18:48 UTC
Labels: invalid

**Comment by marcelloh** [comment] 2017-09-08 20:11
I would say, it is not a duplicate, because the other issue is about fixing the structure and mine is about fixing the documentation.
