### ISSUE TITLE
undefined method PhpOffice\PhpSpreadsheet\Calculation\Calculation::_getMatrixDimensions()

### ISSUE THREAD

**Issue by thezombieguy** [PHPOffice/PhpSpreadsheet#340] opened 2018-01-18 01:13 UTC
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

This is my first bug report. Please go easy on me if i screw it up.  :)

### What is the expected behavior?

Whenh loading spreadsheet active sheet using the toArray(null, true, true, true) method  with a formula like so: =A2&"_001_"&TEXT(ROWS($D$2:D2),"000") it should load all the cells into an array as expected.

### What is the current behavior?
Doing this generates an error: 

```
Fatal error: Uncaught Error: Call to undefined method PhpOffice\PhpSpreadsheet\Calculation\Calculation::_getMatrixDimensions() in
/public_html/dev/phpexcel/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/LookupRef.php:229
Stack trace:
#0 [internal function]: PhpOffice\PhpSpreadsheet\Calculation\LookupRef::ROWS(Array)
#1
/public_html/dev/phpexcel/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php(3749): call_user_func_array(Array, Array)
#2
/public_html/dev/phpexcel/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php(2729): PhpOffice\PhpSpreadsheet\Calculation\Calculation->processTokenStack(Array, 'D2', Object(PhpOffice\PhpSpreadsheet\Cell\Cell))
#3 /public_html/dev/phpexcel/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php(2526): PhpOffice\PhpSpreadsheet\Calculation\Calculation->_calcul
```

On line 2791 of Calculation.php is the following:

```php
public static function getMatrixDimensions(&$matrix)
```

but Lookup.php is trying to call 

```php
Calculation::_getMatrixDimensions($cellAddress); 
```

which is an undefined method. See line 148 and 229 of Lookup.php

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

You need an excel file with a formula similar to the one above to generate the error.

Project | Name | Value | UniqueID
-- | -- | -- | --
DCM | Bob | 12 | DCM_001_001

Where Unique ID is the formula inserted under UniqueID to generate the value.

![test2](https://user-images.githubusercontent.com/2289984/35075636-1ae6ed64-fba9-11e7-927b-59ed8cc07bd7.png)

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load('/path/to/your/excel/file.xlsx');


$sheetData = $spreadsheet->getActiveSheet()->toArray(null, true, true, true);
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.0

**Comment by PowerKiKi** [comment] 2018-01-18 05:33
Duplicate of #336

**Closed by PowerKiKi** 2018-01-18 05:33 UTC
