### ISSUE TITLE
"Segmentation fault" occurs when 'setCellVale' is called

### ISSUE THREAD

**Issue by mumubusu** [PHPOffice/PhpSpreadsheet#2269] opened 2021-08-13 09:55 UTC
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the current behavior?
This happen when there is a lot of data. For example, more than 3000 rows

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', '平台');
$sheet->setCellValue('B1', '门店');
$sheet->setCellValue('C1', '商品名称');
$sheet->setCellValue('D1', '条形码');
$sheet->setCellValue('E1', '商品分类');
$sheet->setCellValue('F1', 'ERP商品编码');
$sheet->setCellValue('G1', '是否对码');
$sheet->setCellValue('H1', '门店库存');
$sheet->setCellValue('I1', '门店价格');
$sheet->setCellValue('J1', '锁定状态');
$sheet->setCellValue('K1', '同步时间');
$sheet->setCellValue('L1', '上架状态');

foreach($datas as $index => $row) {

$sheet->setCellValue('A' . $index, $row[0]);
$sheet->setCellValue('B' . $index, $row[1]);
$sheet->setCellValue('C' . $index, $row[2]);
$sheet->setCellValue('D' . $index, $row[3]);
$sheet->setCellValue('E' . $index, $row[4]);
$sheet->setCellValue('F' . $index, $row[5]);
$sheet->setCellValue('G' . $index, $row[6]);
$sheet->setCellValue('H' . $index, $row[7]);

$sheet->setCellValue('I' . $index, $row[8]);
$sheet->setCellValue('J' . $index, $row[9]);

$sheet->setCellValue('K' . $index, $row[10]);
$sheet->setCellValue('L' . $index, $row[11]);

}
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.18

**Comment by MarkBaker** [comment] 2021-08-13 10:25
Duplicate of [Issue #2270](https://github.com/PHPOffice/PhpSpreadsheet/issues/2270)

**Closed by MarkBaker** 2021-08-13 10:25 UTC
