### ISSUE TITLE
Allow empty arguments on VLOOKUP as in excel

### ISSUE THREAD

**Issue by marcusdiy** [PHPOffice/PhpSpreadsheet#2120] opened 2021-05-26 23:00 UTC
This is:
a problem with the current argument handling behavour wich make it incompatibile.
VLOOKUP function can accept 3 or 4 arguments, but it wont work if the 4 argument is empty
```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question
```

### What is the expected behavior?
in excel if you leave the 4 argument blank it will deal with it as thoose were 3
VLOOKUP(E124;'SHEET'!A1:B10;2;) --> error
VLOOKUP(E124;'SHEET'!A1:B10;2) --> works

The problem seems to be present only when, maybe its a formatting error allowed in excel?
```
=IF(A1="test";VLOOKUP(E124;'SHEET'!A1:B10;2;);456)
```
### What is the current behavior?
Error loading file: SHEET!R118 -> internal error

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.17.1

**Comment by MarkBaker** [comment] 2021-05-27 09:33
The issue is with the trailing argument separator.... without that, only three arguments will be passed to the internal implementation of the function, and it will correctly default the missing argument; but with the trailing argument separator, the calculation engine passes a `null` value through as the fourth argument, so it doesn't default correctly.

There are a lot of functions in Excel that allow missing arguments (not always the trailing arguments either, which is why we pass a null value), and in most cases when a null is passed because of the argument separator, we convert that to the default, but there's a few exceptions where that logic is missing. Many of them have been fixed already with the latest refactoring of the Excel function implementations; but I missed a few in the Lookup/Reference functions - both `HLOOKUP()` and `VLOOKUP()`, and also `ADDRESS()`

**Comment by marcusdiy** [comment] 2021-05-27 10:11
Thanks! @MarkBaker

**Comment by oleibman** [comment] 2024-05-07 03:29
Closing, issue resolved 3 years ago.

**Closed by oleibman** 2024-05-07 03:29 UTC
