### ISSUE TITLE
XLSM support

### ISSUE THREAD

**Issue by artggd** [PHPOffice/PhpSpreadsheet#30] opened 2016-10-19 14:03 UTC
Hi there,

I found PhpExcel a great library and wanted to give a go to PhpSpreadsheet to import XLSM files into my website but I am facing an issue.

When loading an XLSM file using `IOFactory::load($filename)`, the Excel2007 reader is created (as expected) but when the `readStyle()` method is then called, the second argument is expected to be an stdClass but a SimpleXMLElement is given, thus throwing an exception.

As a side note, is PhpSpreadsheet ready for production yet or would you recommend I'd rather stick to PhpExcel?

Cheers.

**Comment by PowerKiKi** [comment] 2016-10-21 12:45
Duplicate of #21, was fixed in 2b41bdbf4eb44b7d76f875f04509318265517b1f two weeks ago.

PhpSpreadsheet does not have any release yet, so it is not production ready, but it **might** be development ready... If you accept that it breaks a few times before release, then keep using it. If you don't care for new code and prefer stability, stick to PHPExcel.

**Closed by PowerKiKi** 2016-10-21 12:45 UTC
