### ISSUE TITLE
Error on export xlsx when DataValidation

### ISSUE THREAD

**Issue by Gabriel438** [PHPOffice/PhpSpreadsheet#2395] opened 2021-11-11 17:50 UTC
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
![image](https://user-images.githubusercontent.com/46533367/141344920-4cbeb924-bb6f-46cb-9a17-128b557cd53d.png)

### What is the current behavior?
![image](https://user-images.githubusercontent.com/46533367/141345009-9713d32e-ee06-479c-a95a-13f1b92eecf2.png)

### What are the steps to reproduce?

    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();
    $sheet = $spreadsheet->getSheet(0);
    $validation = $sheet->getCell('B2')->getDataValidation();
    $validation->setType(\PhpOffice\PhpSpreadsheet\Cell\DataValidation::TYPE_LIST);
    $validation->setFormula1('"A, B, C, D"');
    $validation->setError('Select one from the drop down list.');

    $writer = new Xlsx($spreadsheet);
    $name = str_replace('.','',str_replace(' ', '',microtime().date('Y h'))).'.xlsx';
    $path = 'arquivos/modelo_planilha/'.$name;
    $writer->save($path);

### Which versions of PhpSpreadsheet and PHP are affected?

PHP: 7.3
PhpSpreadsheet : 1.19

**Comment by oleibman** [comment] 2021-11-11 19:46
Closed as duplicate of #2368, for which there are as-yet-unmerged PRs which you might be able to test.

**Closed by oleibman** 2021-11-11 19:46 UTC
