### ISSUE TITLE
Please add a pre-generated autoloader to the source

### ISSUE THREAD

**Issue by ant-g** [PHPOffice/PhpSpreadsheet#387] opened 2018-02-21 17:12 UTC
This is:

```
- [ ] a bug report
- [X ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Deploy PhpSpreadsheet without issues

### What is the current behavior?
Cannot deploy because composer.json generates a mysterious error that I (or anyone so far on StackExchange) can't solve.  
` - The requested package phpoffice/phpspreadsheet No version set (parsed as 1.0.0) is satisfiable by phpoffice/phpspreadsheet[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.`

Why have you made deployment of your library dependent on Composer?
Other libraries offer the composer install, but also a pre-generated set of files so that if you don't have composer (or it doesn't work for some reason, or you're not familiar with it) one can still get going.

Is it possible for you to add an autoloader file that if included will allow the library to operate?

**Comment by PowerKiKi** [comment] 2018-02-22 08:17
This won't happen. Composer is and will be mandatory.

Start from scratch and re-read the install instruction: http://phpspreadsheet.readthedocs.io/en/develop/#installation

**Comment by PowerKiKi** [comment] 2018-02-22 08:18
Duplicate of #368

**Closed by PowerKiKi** 2018-02-22 08:17 UTC
