### ISSUE TITLE
Upgrade psr/simple-cache to Version 3

### ISSUE THREAD

**Issue by sotten** [PHPOffice/PhpSpreadsheet#2697] opened 2022-03-18 20:40 UTC
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Clean Laravel 9 with PHP8.1 should work with `maatwebsite/excel.`
### What is the current behavior?
Cannot be installed.

### What are the steps to reproduce?
 Command `composer require maatwebsite/excel` throws the following error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - maatwebsite/excel[3.1.36, ..., 3.1.x-dev] require phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0, ..., 1.22.0].
    - maatwebsite/excel[3.1.0, ..., 3.1.25] require php ^7.0 -> your php version (8.1.3) does not satisfy that requirement.
    - maatwebsite/excel[3.1.26, ..., 3.1.35] require illuminate/support 5.8.*|^6.0|^7.0|^8.0 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - phpoffice/phpspreadsheet[1.18.0, ..., 1.22.0] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires maatwebsite/excel ^3.1 -> satisfiable by maatwebsite/excel[3.1.0, ..., 3.1.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require maatwebsite/excel:*" to figure out if any version is installable, or "composer require maatwebsite/excel:^2.1" if you know which you need.
```
`psr/simple-cache` should be `"^3.0"`

### Which versions of PhpSpreadsheet and PHP are affected?
Larvel 9.5.1 PHP 8.1.3

**Comment by MarkBaker** [comment] 2022-03-18 22:03
Duplicate of [Issue #2468](https://github.com/PHPOffice/PhpSpreadsheet/issues/2468), and see [PR #2667](https://github.com/PHPOffice/PhpSpreadsheet/pull/2667)

**Closed by MarkBaker** 2022-03-18 22:03 UTC
Labels: duplicate
