### ISSUE TITLE
Class not found (ZipStream\Option\Archive) in PHP 8.2.

### ISSUE THREAD

**Issue by JohnKlein985** [PHPOffice/PhpSpreadsheet#3902] opened 2024-02-14 21:56 UTC
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Class Xlsx.php in Writer should successfully create a zip stream.

### What is the current behavior?
Class not found ZipStream\Option\Archive

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory as Excel;

$doc = new DOMDocument();
$xsl = new XSLTProcessor();

$formatFile = "/tmp/format.xsl";
$file_handle = fopen($formatFile,'w');
$content = '<?xml version="1.0"?>
<xsl:stylesheet version="1.0" xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:msxsl="urn:schemas-microsoft-com:xslt" xmlns:user="urn:my-scripts" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">

	<xsl:template match="Data">
		<?mso-application progid="Excel.Sheet"?>
		<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet" xmlns:html="http://www.w3.org/TR/REC-html40">
		<Styles>
			<Style ss:ID="Default" ss:Name="Normal"><Alignment ss:Vertical="Bottom"/><Font ss:Size="10" ss:Color="#000000"/></Style>
		</Styles>
        <Worksheet ss:Name="Example">	
		<Table>
		   
		</Table>
		</Worksheet>	
		</Workbook>
	</xsl:template>
	
</xsl:stylesheet>';
fwrite($file_handle, $content);
fclose($file_handle);

$doc->load("/tmp/format.xsl");
$xsl->importStyleSheet($doc);


$fileXML = "/tmp/example.xml";
$file_handle = fopen($fileXML,'w');
$content = '<?xml version="1.0"?><Data></Data>';
fwrite($file_handle, $content);
fclose($file_handle);

$doc->load("/tmp/example.xml");

$filePathXLS = "/tmp/example.xls";
$filePathXLSX = "/tmp/example.xlsx";

$invalidXsl = new DOMDocument();
$invalidXsl->loadXML($xsl->transformToXML($doc));
$special = $invalidXsl->createProcessingInstruction("mso-application",'progid="Excel.Sheet"');
$invalidXsl->insertBefore($special,$invalidXsl->firstChild);
$invalidXsl->save($filePathXLS);

$spreadsheet = Excel::load($filePathXLS);
$writer = Excel::createWriter($spreadsheet, 'Xlsx');					
$writer->save($filePathXLSX);
```

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Only tested with xlsx, but it will apply to everything trying to create a Zip.

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 2.0.0 with PHP 8.2.

**Comment by oleibman** [comment] 2024-02-15 05:02
Closing as duplicate of issue #3615. There is a problem in your environment, possibly due to Composer caching. The instructions in https://github.com/PHPOffice/PhpSpreadsheet/issues/3615#issuecomment-1595846986 should be helpful in getting everything correct.

**Closed by oleibman** 2024-02-15 05:02 UTC

**Comment by JohnKlein985** [comment] 2024-02-16 17:07
> Closing as duplicate of issue #3615. There is a problem in your environment, possibly due to Composer caching. The instructions in [#3615 (comment)](https://github.com/PHPOffice/PhpSpreadsheet/issues/3615#issuecomment-1595846986) should be helpful in getting everything correct.

Clearing composer cache and reinstalling did not correct the issue. The only solution I have is to alter the vendor code. I have had to fork this repo in order to get local environments working for all of my developers.

**Comment by JohnKlein985** [comment] 2024-02-16 17:28
Fixed my issue by referring to this post: https://github.com/PHPOffice/PhpSpreadsheet/issues/3616
